version: '3.4'
services:
  shopping_cart:
    restart: always
    image: shopping-cart:latest
    network_mode: host
    ports:
      - "8080:8080"
    environment:
      - DEBUG=false
      - SC_ACCESS_TOKEN_SECRET_KEY=YourToken
      - SC_JWT_SECRET_KEY=YourSecret
      - SC_JWT_CLAIM=YourClaim
      - SC_ADMIN_USER_TOKEN=YourAdminToken
      - SC_PASSWORD_SALT=YourEncryptionKey
      - SC_APP_ENV=test
      - SC_POSTGRES_PASSWORD=my-password
