addSbtPlugin("org.typelevel" % "sbt-tpolecat" % "0.5.2")
addSbtPlugin("io.spray"                  % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.github.sbt"            % "sbt-native-packager" % "1.9.12")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.10.0")